language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install -e .
  - pip install codecov 
# command to run tests
script: py.test
after_success:
  - codecov
