language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install -e .
  - pip install coverage 
# command to run tests
script: py.test
after_success:
    - if [[ $ENV == python=3.6* ]]; then
        codecov;
      fi
